
<?php if ($this->checkIsAddressVerifiyed()): ?>
    <h1 class="error-msg"><?php echo $this->checkIsAddressVerifiyed() ?></h1>
<?php endif; ?>
<?php if ($this->getTitle()): ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle() ?></h1>
    </div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml() ?>
            </li>
            <li class="wide">
                <label for="company"><?php echo $this->__('Company') ?></label>
                <div class="input-box">
                    <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                    </div>
                </div>
                <div class="field">
                    <label for="fax"><?php echo $this->__('Fax') ?></label>
                    <div class="input-box">
                        <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <ul class="form-list">

            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li class="wide">
                    <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                    <div class="input-box">
                        <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
            <?php endif; ?>
            <li class="wide">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </div>

                <input type="hidden" name="speedy_site_id" id="speedy_site_id" value="<?php echo $this->escapeHtml($this->getAddress()->getSpeedySiteId()) ?>" />


            </li>
            <li class="fields">
                <div class="field" >
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" style="width: 50px" name="postcode" size="4" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <label for=""><?php echo $this->__("Choose Speedy office") ?></label>
                <div class="field">
                    <?php if ($this->getAddress()->getSpeedyOfficeId()): ?>
                        <input type="checkbox" name="speedy_office_chooser" id="speedy_office_chooser" checked="checked" />
                    <?php else: ?>
                        <input type="checkbox" name="speedy_office_chooser" id="speedy_office_chooser" />
                    <?php endif; ?>
                </div>
            </li>
            <li>
            <?php if ($this->getAddress()->getSpeedyOfficeId()): ?>
                <div id="speedy_office_address">
                <?php else: ?>
                    <div id="speedy_office_address" style="display: none">
                    <?php endif; ?>
                  <ul>
                    <li class="wide" id="speedy_office_textbox">
                        <div class="field">
                            <label for=""></label>
                            <div class="input-box">

                                <?php if ($this->getAddress()->getSpeedyOfficeId()): ?>
                                    <input type="text" name="speedy_office_locator" id="speedy_office_locator" class="input-text" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"/>
                                    <input type="hidden" name="speedy_office_id" id="speedy_office_id" value="<?php echo $this->escapeHtml($this->getAddress()->getSpeedyOfficeId()) ?>" />
                                <?php else: ?>

                                    <input type="text" name="speedy_office_locator" id="speedy_office_locator" class="input-text" />
                                    <input type="hidden" name="speedy_office_id" id="speedy_office_id" />
                                <?php endif; ?>
                            </div>
                        </div>
                    </li>

                        </ul>


                </div>
                </li>

                <li>
                <?php if ($this->getAddress()->getSpeedyOfficeId()): ?>

                    <div id="speedy_normal_address" style="display: none">
                    <?php else: ?>
                        <div id="speedy_normal_address">    
                           
                        <?php endif; ?>
                             <ul>
                        <li class="wide">
                            <div class="field">

                                <label for="speedy_quarter_name"><?php echo $this->__('Quarter') ?></label>
                                <div class="input-box">
                                    <input type="text" class="input-text" name="speedy_quarter_name" id="speedy_quarter_name" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyQuarterName()) ?>"/><br />
                                    <input type="hidden" name="speedy_quarter_id" id="speedy_quarter_id" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyQuarterId()) ?>"/></div></div>

                            <input type="hidden" name="speedy_street_id" id="speedy_street_id" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyStreetId()) ?>" />
                        </li>
                        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="wide">
                            <label for="speedy_street"><?php echo $this->__('speedy street name');  ?></label>
                            <div class="input-box">
                                <input type="text" name="speedy_street_name" value="<?php echo $this->escapeHtml($this->getAddress()->getSpeedyStreetName()) ?>" id="speedy_street" class="input-text"  />
                            </div>
                            <div id="street_holder" style="display: none">
                                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </div>
                        </li>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

                        <li class="fields">
                            <div class="field">
                                <label for="speedy_street_number"><?php echo $this->__('Street Number') ?></label>
                                <div class="input-box">

                                    <input type="text" class="input-text" name="speedy_street_number" id="speedy_street_number" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyStreetNumber()) ?>" /></div>
                            </div>
                            <div class="field">
                                <label for="speedy_block_number"><?php echo $this->__('Blok') ?></label>
                                <div class="input-box">
                                    <input type="text" class="input-text" name="speedy_block_number" id="speedy_block_number" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyBlockNumber()) ?>" /></div></div>

                        </li>

                        <li class="fields">
                            <div class="field">
                                <label for=""><?php echo $this->__("Entrance") ?></label>
                                <div class="input-box">
                                    <input type="text" name="speedy_entrance" id="speedy_entrance" class="input-text" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyEntrance()) ?>" /></div>
                            </div>
                            <div class="field">
                                <label for=""><?php echo $this->__("Floor") ?></label>
                                <div class="input-box">
                                    <input type="text" name="speedy_floor" id="speedy_floor" class="input-text" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyFloor()) ?>"/></div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for=""><?php echo $this->__("Apartment") ?></label>
                                <div class="input-box">
                                    <input type="text" name="speedy_apartment" id="speedy_apartment" class="input-text" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyApartment()) ?>" /></div>
                            </div>
                        </li>
                        <li class="wide">
                            <div class="field">
                                <label for=""><?php echo $this->__("Address note") ?></label>
                                <div class="input-box">
                                    <input class="input-text" type="text" id="speedy_address_note" name="speedy_address_note" value="<?php echo $this->htmlEscape($this->getAddress()->getSpeedyAddressNote()) ?>" />

                                </div>
                            </div>
                        </li>
                        <li class="wide">
                            <div class="field">
                                <div id="speedyError" style="display: none" class="validation-failed">
                                    <?php echo $this->__("valid_address_desc") ?>
                                </div>
                            </div>
                        </li>
                            </ul>
                    </div>
                    </li>
                    <div class="field" style="display: none">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>

                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                        </div>
                        <script type="text/javascript">
                            //<![CDATA[
                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                        </script>
                    </div>
                    </li>
                    <li class="fields">
                        <!--<div class="field">
                            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>-->
                        <div class="field" style="display: none">
                            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                    </li>
                    <li<?php if ($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                        <?php if ($this->isDefaultBilling()): ?>
                            <strong><?php echo $this->__('Default Billing Address') ?></strong>
                        <?php elseif ($this->canSetAsDefaultBilling()): ?>
                            <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                        <?php else: ?>
                            <input type="hidden" name="default_billing" value="1" />
                        <?php endif; ?>
                    </li>
                    <li<?php if ($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                        <?php if ($this->isDefaultShipping()): ?>
                            <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                        <?php elseif ($this->canSetAsDefaultShipping()): ?>
                            <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                        <?php else: ?>
                            <input type="hidden" name="default_shipping" value="1" />
                        <?php endif; ?>
                    </li>


                    </ul>
                </div>
                <div class="buttons-set">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                    <button type="submit" title="<?php echo $this->__('Save Address') ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
                </div>

                </form>
                <script type="text/javascript">
                    //<![CDATA[
                    var dataForm = new VarienForm('form-validate', true);
                    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

                    //]]>


                    $j('document').ready(function() {
<?php if ($this->_isFullNomenclature): ?>
                            var isFullNomenclature = "<?php echo $this->_isFullNomenclature; ?>";
<?php else: ?>
                            var isFullNomenclature = 0;
<?php endif; ?>


                        var siteName = '';
                        var quarterName = '';
                        var streetName = '';
                        var blokName = '';
                        var officeName = '';


                        function initFields() {

                            if ($j('#speedy_quarter_name').val() != '') {
                                quarterName = $j('#speedy_quarter_name').val();
                            }


                            if ($j('#speedy_street').val() != '') {
                                streetName = $j('#speedy_street').val();
                            }


                            if ($j('#speedy_block_number').val() != '') {
                                blokName = $j('#speedy_block_number').val();
                            }

                            if ($j('#speedy_office_locator').val() != '') {
                                officeName = $j('#speedy_office_locator').val();
                            }
                        }

                        initFields();

                        $j('#speedy_office_chooser').change(function(evt) {
                            if ($j(this).is(':checked')) {
                                $j('#speedy_normal_address').hide().find('input').val('');
                                $j('#speedy_office_address').show();
                            } else {
                                $j('#speedy_normal_address').show();
                                $j('#speedy_office_address').hide().find('input').val('');
                                $j('#speedy_office_id, #speedy_street,#speedy_office_locator').val('');

                            }
                        });
                        $j('#city, div#speedy_normal_address input, #speedy_office_address input').keydown(function(e) {


                            if (e.which == 13) {
                                e.preventDefault();
                                checkFields(e);
                                var isValid = validateAddress();

                                if (isValid) {
                                    //$j('#form-validate').submit();
                                    dataForm.submit();

                                } else {
                                    $j('div#speedyError').show();
                                }

                                return false;
                            }
                        });






                        $j('#city,div#speedy_normal_address input, #speedy_office_address input').blur(function(evt) {



                            checkFields(evt)



                        });


                        function checkFields(target) {

                            var evtTarget = $j(target.target);

                            if (evtTarget.attr('id') == 'city') {
                                if (siteName != evtTarget.val()) {

                                    evtTarget.val('')
                                    $j('#speedy_site_id').val('')
                                    $j('#zip').val('')
                                    updateForm()
                                } else if (evtTarget.val() == "") {

                                    updateForm();
                                    $j('#speedy_site_id').val('')
                                    $j('#zip').val('')
                                } else {
                                    updateForm(true);
                                }
                            }


                            if (!$j('#speedy_site_id').val()) {
                                evtTarget.val('');
                                return;
                            }

                            if (evtTarget.attr('id') == 'speedy_street') {

                                if (isFullNomenclature == 'FULL' && $j('#speedy_street_id').val() == false) {
                                    evtTarget.val('')
                                    $j('#speedy_street_id').val('');
                                }


                                else if (evtTarget.val() != streetName && isFullNomenclature == 'FULL') {
                                    evtTarget.val('')
                                    $j('#speedy_street_id').val('');
                                } else if ($j('#speedy_street_id').val() != '' && isFullNomenclature != 'FULL' && evtTarget.val() != streetName) {
                                    evtTarget.val('')
                                    $j('#speedy_street_id').val('');
                                }else if(isFullNomenclature == 'NO' || isFullNomenclature == 'PARTIAL'){
                                                                evtTarget.val(evtTarget.val().toUpperCase())
                                                            }

                            } else if (evtTarget.attr('id') == 'speedy_quarter_name') {



                                if (isFullNomenclature == 'FULL' && $j('#speedy_quarter_id').val() == false) {
                                    evtTarget.val('')
                                    $j('#speedy_quarter_id').val('');

                                }


                                else if (evtTarget.val() != quarterName && isFullNomenclature == 'FULL') {
                                    evtTarget.val('')
                                    $j('#speedy_quarter_id').val('');

                                } else if ($j('#speedy_quarter_id').val() != '' && evtTarget.val() != quarterName) {
                                    evtTarget.val('')
                                    $j('#speedy_quarter_id').val('');
                                }else if(isFullNomenclature == 'NO' || isFullNomenclature == 'PARTIAL'){
                                                                evtTarget.val(evtTarget.val().toUpperCase())
                                                            }

                            } else if (evtTarget.attr('id') == 'speedy_office_locator') {


                                if ($j('#speedy_office_id').val() == false) {
                                    evtTarget.val('')

                                    $j('#speedy_office_id').val('');
                                    $j('#speedy_street').val('')
                                }


                                else if (evtTarget.val() != officeName) {
                                    evtTarget.val('')
                                    $j('#speedy_office_id').val('');
                                    $j('#speedy_street').val('')
                                } else if ($j('#speedy_office_id').val() != '' && evtTarget.val() != officeName) {
                                    evtTarget.val('')
                                    $j('#speedy_office_id').val('');
                                    $j('#speedy_street').val('')
                                }


                            } else if (evtTarget.attr('id') == 'speedy_block_number') {
                                evtTarget.val(evtTarget.val().toUpperCase())
                            } else if (evtTarget.attr('id') == 'speedy_entrance') {
                                evtTarget.val(evtTarget.val().toUpperCase())
                            } else if (evtTarget.attr('id') == 'speedy_floor') {
                                evtTarget.val(evtTarget.val().toUpperCase())
                            } else if (evtTarget.attr('id') == 'speedy_apartment') {
                                evtTarget.val(evtTarget.val().toUpperCase())
                            } else if (evtTarget.attr('id') == 'speedy_address_note') {
                                evtTarget.val(evtTarget.val().toUpperCase())
                            }
                        }

                        _initListeners();

                        function _initListeners() {

                            $j('#city').autocomplete({
                                source: function(request, response) {

                                    $j.ajax({
                                        url: "<?php echo Mage::getUrl("speedyshippingfront/address/getSite"); ?>",
                                        dataType: "json",
                                        data: {
                                            term: request.term
                                        },
                                        success: function(data) {
                                            response(data);
                                        }
                                    });
                                }
                                , minLength: 1
                                        , select: function(event, ui) {
                                    updateForm();
                                    $j(this).val(ui.item.label);
                                    siteName = ui.item.label;
                                    $j('#speedy_site_id').val(ui.item.value)

                                    $j('#zip').val(ui.item.post_code)
                                    $j('#country').val('BG');
                                    $j('#region_id').hide();

                                    $j('#region').show().val(ui.item.region)

                                    if (ui.item.is_full_nomenclature == 'NO') {
                                        isFullNomenclature = 'NO';
                                        disableAutocomplete()
                                    } else if (ui.item.is_full_nomenclature == 'PARTIAL') {

                                        isFullNomenclature = 'PARTIAL';
                                        enableAutocomplete();
                                    } else {
                                        isFullNomenclature = 'FULL';
                                        enableAutocomplete();

                                    }

                                    return false;
                                }});


                            $j('#speedy_office_locator').autocomplete({
                                source: function(request, response) {

                                    $j.ajax({
                                        url: "<?php echo Mage::getUrl("speedyshippingfront/address/getOffices"); ?>",
                                        dataType: "json",
                                        data: {
                                            term: request.term,
                                            cityid: $j('#speedy_site_id').val()
                                        },
                                        success: function(data) {
                                            
                                            response(data);
                                        }
                                    });
                                }
                                ,response: function(event, ui){
                                $j(this).autocomplete("option", "disabled", false);

                                }
                                , minLength: 0
                                        , select: function(event, ui) {
                                    $j(this).val(ui.item.label);
                                    officeName = ui.item.label;
                                    $j('#speedy_office_id').val(ui.item.value);
                                    $j('#speedy_street').val(ui.item.label);
                                    initSiteData(ui);
                                    return false;
                                }}).focus(function() {
                                if ($j('#speedy_site_id').val()) {
                                    //Use the below line instead of triggering keydown
                                    $j(this).autocomplete("search")
                                }
                            });


                            $j('#speedy_quarter_name').autocomplete({
                                source: function(request, response) {

                                    $j.ajax({
                                        url: "<?php echo Mage::getUrl("speedyshippingfront/address/getQuarter"); ?>",
                                        dataType: "json",
                                        data: {
                                            term: request.term,
                                            cityid: $j('#speedy_site_id').val()
                                        },
                                        success: function(data) {
                                            response(data);
                                        }
                                    });
                                }
                                , minLength: 1
                                        , select: function(event, ui) {
                                    $j(this).val(ui.item.label);
                                    quarterName = ui.item.label;
                                    $j('#speedy_quarter_id').val(ui.item.value)
                                    return false;
                                }});

                            $j('#speedy_street').autocomplete({
                                source: function(request, response) {

                                    $j.ajax({
                                        url: "<?php echo Mage::getUrl("speedyshippingfront/address/getStreets"); ?>",
                                        dataType: "json",
                                        data: {
                                            term: request.term,
                                            cityid: $j('#speedy_site_id').val()
                                        },
                                        success: function(data) {
                                            response(data);
                                        }
                                    });
                                }
                                , minLength: 1
                                        , select: function(event, ui) {
                                    $j(this).val(ui.item.label);
                                    streetName = ui.item.label;
                                    $j('#speedy_street_id').val(ui.item.value)

                                    return false;
                                }});


                        }

                        $j('#speedy_block_number').autocomplete({
                            source: function(request, response) {

                                $j.ajax({
                                    url: "<?php echo Mage::getUrl("speedyshippingfront/address/getBlock"); ?>",
                                    dataType: "json",
                                    data: {
                                        term: request.term,
                                        cityid: $j('#speedy_site_id').val()
                                    },
                                    success: function(data) {
                                        response(data);
                                    }
                                });
                            }
                            , minLength: 1
                                    , select: function(event, ui) {
                                $j(this).val(ui.item.label);

                                return false;
                            }});


                        function initSiteData(jsonResponse){
                                $j('#speedy_site_id').val(jsonResponse.item.site_id)
                                $j('#zip').val(jsonResponse.item.post_code)
                                $j('#region').val(jsonResponse.item.region)

                                siteName = jsonResponse.item.site_name;
                                $j('#city').val(siteName);
                                if (jsonResponse.item.is_full_nomenclature == 'NO') {
                                    isFullNomenclature = 'NO';
                                    disableAutocomplete()
                                } else if (jsonResponse.item.is_full_nomenclature == 'PARTIAL') {

                                    isFullNomenclature = 'PARTIAL';
                                    enableAutocomplete();
                                } else {
                                    isFullNomenclature = 'FULL';
                                    enableAutocomplete();

                                }
                        }


                        function updateForm(enable) {

                            if (enable) {

                                $j('div#speedy_normal_address input, #speedy_office_address input')
                                        .removeAttr('disabled');

                            } else {

                                $j('div#speedy_normal_address input, #speedy_office_address input')
                                        .attr('disabled', 'disabled').val('');
                            }


                        }


                        $j('div button.button ').click(function(evt) {
                            evt.preventDefault();
                            var isValid = validateAddress();

                            if (isValid) {
                                //$j('#form-validate').submit();
                                dataForm.submit();

                            } else {
                                $j('div#speedyError').show();
                            }

                        })



                        function validateAddress() {
                            $j('div#speedyError').hide();
                            var baseForm = '#form-validate';
                            var city_id = $j(baseForm + ' #speedy_site_id').val();
                            var quarter = $j(baseForm + ' #speedy_quarter_name').val();
                            var quarter_id = $j(baseForm + ' #speedy_quarter_id').val();
                            var street = $j(baseForm + ' #speedy_street').val();
                            var street_id = $j(baseForm + ' #speedy_street_id').val();
                            var number = $j(baseForm + ' #speedy_street_number').val();
                            var blockNo = $j(baseForm + ' #speedy_block_number').val();
                            var address_note = $j(baseForm + ' #speedy_address_note').val();

                            var floor_no = $j(baseForm + ' #speedy_floor').val();
                            var entrance = $j(baseForm + ' #speedy_entrance').val();
                            var apartment = $j(baseForm + ' #speedy_apartment').val();

                            var speedy_pick_from_office = $j(baseForm + ' #speedy_office_chooser').is(':checked');
                            var speedy_office_name = $j(baseForm + ' #speedy_office_locator').val();
                            var speedy_office_id = $j(baseForm + ' #speedy_office_id').val();

                            var isValid = 0;

                            if (!city_id) {
                                return false;
                            }

                            if (quarter.length || parseInt(quarter_id)) {
                                if ((street && number) || blockNo || number) {
                                    isValid = 1;
                                }

                            } else if (speedy_pick_from_office && speedy_office_name && parseInt(speedy_office_id)) {
                                isValid = 1;
                            } else if (street.length || parseInt(street_id)) {
                                if (number || blockNo) {
                                    isValid = 1;
                                }
                            }
                            else if (address_note && address_note.length > 4) {
                                isValid = 1;
                            }

                            if (isValid) {
                                var streetAddress = '';

                                var address = '';
                                var note = '';

                                var streetAddress = '';

                                if (speedy_office_name.length > 1) {
                                   // address += speedy_office_name;
                                }

                                if (quarter.length > 1) {
                                    address += ' ' + quarter;
                                }
                                if (street.length > 1) {
                                    address += ' ' + street;
                                }
                                if (number.length >= 1) {
                                    address += " <?php echo $this->__("Street Number") ?>" + number;
                                }
                                if (blockNo.length >= 1) {
                                    address += " <?php echo $this->__("Blok") ?>" + blockNo;
                                }

                                if (entrance.length >= 1) {
                                    address += " <?php echo $this->__("Entrance") ?>" + entrance;
                                }
                                if (floor_no.length >= 1) {
                                    address += " <?php echo $this->__("Floor") ?>" + floor_no;
                                }
                                if (apartment.length >= 1) {
                                    address += " <?php echo $this->__("Apartment") ?>" + apartment;
                                }

                                if (address_note.length > 3) {
                                    note += " " + address_note;
                                }

                                streetAddress = address;

                                if (note != '' && streetAddress.length>0) {
                                    streetAddress += ', ' + note;
                                }else{
                                    streetAddress +=  note;
                                    }

                                $j('#street_1').val(streetAddress);

                                return true;
                            } else {


                                return false;
                            }
                        }


                        function enableAutocomplete() {
                            $j("#speedy_quarter_name, #speedy_street,#speedy_office_locator ").autocomplete("option", "disabled", false);
                        }

                        function disableAutocomplete() {
                            $j("#speedy_quarter_name, #speedy_street,#speedy_office_locator ").autocomplete("option", "disabled", true);
                        }



                    })
                </script>
