<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Exceptionmap
 *
 * @author killer
 */
class Speedy_Speedyshipping_Helper_Exceptionmap extends Mage_Core_Helper_Abstract{
    //put your code here
    private $errorMap = array();
    public function __construct() {
        $errorMap['COMMON_ERROR'] = 'COMMON_ERROR';
        $errorMap['AMOUNT_INSURANCE_OUT_OF_RANGE'] = 'AMOUNT_INSURANCE_OUT_OF_RANGE';
        $errorMap['AMOUNT_CASH_ON_DELIVERY_OUT_OF_RANGE'] = 'AMOUNT_CASH_ON_DELIVERY_OUT_OF_RANGE';
        $errorMap['AMOUNT_MONEY_TRANSFER_REQ_OUT_OF_RANGE'] = 'AMOUNT_MONEY_TRANSFER_REQ_OUT_OF_RANGE';
        $errorMap['WEIGHT_NOT_IN_RANGE'] = 'WEIGHT_NOT_IN_RANGE';
        $errorMap['DOCUMENTS_NOT_ALLOWED_FOR_THIS_SERVICE_AND_SITES'] = 'DOCUMENTS_NOT_ALLOWED_FOR_THIS_SERVICE_AND_SITES';
        $errorMap['DOCUMENT_PICKINGS_CAN_CONSIST_OF_ONLY_ONE_PARCEL'] = 'DOCUMENT_PICKINGS_CAN_CONSIST_OF_ONLY_ONE_PARCEL';
        $errorMap['DOCUMENT_PICKINGS_ARE_NOT_ALLOWED_TO_HAVE_INSURANCE'] = 'DOCUMENT_PICKINGS_ARE_NOT_ALLOWED_TO_HAVE_INSURANCE';
        $errorMap['DOCUMENT_PICKINGS_CANNOT_BE_PALLETIZED'] = 'DOCUMENT_PICKINGS_CANNOT_BE_PALLETIZED';
        $errorMap['FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_RECEIVER_SITE'] = 'FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_RECEIVER_SITE';
        $errorMap['FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_SERVICE'] = 'FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_SERVICE';
        $errorMap['INVALID_FIXED_TIME_FOR_DELIVERY'] = 'INVALID_FIXED_TIME_FOR_DELIVERY';
        $errorMap['NO_MORE_THAN_3_PHONE_NUMBERS_EXPECTED'] = 'NO_MORE_THAN_3_PHONE_NUMBERS_EXPECTED';
        $errorMap['INVALID_PHONE_NUMBER'] = 'INVALID_PHONE_NUMBER';
        $errorMap['LOGGED_CLIENT_OBJECT_MUST_BE_PAYER_OR_SENDER'] = 'LOGGED_CLIENT_OBJECT_MUST_BE_PAYER_OR_SENDER'; 
        $errorMap['INVALID_PARCELS_INFO'] = 'INVALID_PARCELS_INFO'; 
        $errorMap['INVALID_TAKING_DATE'] = 'INVALID_TAKING_DATE'; 
        $errorMap['INVALID_RET_TO_CLIENT_ID'] = 'INVALID_RET_TO_CLIENT_ID'; 
        $errorMap['REQUIRED_BRINGING_TO_OFFICE'] = 'REQUIRED_BRINGING_TO_OFFICE'; 
        $errorMap['DELIVERY_FROM_ADDRESS_TO_ADDRESS_NOT_ALLOWED'] = 'DELIVERY_FROM_ADDRESS_TO_ADDRESS_NOT_ALLOWED'; 
        $errorMap['DELIVERY_FROM_ADDRESS_TO_OFFICE_NOT_ALLOWED'] = 'DELIVERY_FROM_ADDRESS_TO_OFFICE_NOT_ALLOWED'; 
        $errorMap['DELIVERY_FROM_OFFICE_TO_ADDRESS_NOT_ALLOWED'] = 'DELIVERY_FROM_OFFICE_TO_ADDRESS_NOT_ALLOWED'; 
        $errorMap['DELIVERY_FROM_OFFICE_TO_OFFICE_NOT_ALLOWED'] = 'DELIVERY_FROM_OFFICE_TO_OFFICE_NOT_ALLOWED';
        $errorMap['MISSING_REQUIRED_VALUE_FIXED_TIME_FOR_DELIVERY'] = 'MISSING_REQUIRED_VALUE_FIXED_TIME_FOR_DELIVERY';
        $errorMap['MISSING_REQUIRED_VALUE_CONTENTS'] = 'MISSING_REQUIRED_VALUE_CONTENTS';
        $errorMap['MISSING_REQUIRED_VALUE_PACKING'] = 'MISSING_REQUIRED_VALUE_PACKING';
        $errorMap['MISSING_REQUIRED_VALUE_PARTNER_NAME'] = 'MISSING_REQUIRED_VALUE_PARTNER_NAME';
        $errorMap['MISSING_REQUIRED_VALUE_ADDRESS'] = 'MISSING_REQUIRED_VALUE_ADDRESS';
        $errorMap['MISSING_REQUIRED_VALUE_PHONE_SENDER'] = 'MISSING_REQUIRED_VALUE_PHONE_SENDER';
        $errorMap['MISSING_REQUIRED_VALUE_PHONE_RECEIVER'] = 'MISSING_REQUIRED_VALUE_PHONE_RECEIVER';
        $errorMap['MISSING_REQUIRED_VALUE_BOL'] = 'MISSING_REQUIRED_VALUE_BOL';
        $errorMap['MISSING_REQUIRED_VALUE_WEIGHT_DECLARED'] = 'MISSING_REQUIRED_VALUE_WEIGHT_DECLARED';
        $errorMap['VALUE_OUT_OF_RANGE_PARCEL_COUNT'] = 'VALUE_OUT_OF_RANGE_PARCEL_COUNT';
        $errorMap['VALUE_OUT_OF_RANGE_SIZE'] = 'VALUE_OUT_OF_RANGE_SIZE';
        $errorMap['VALUE_OUT_OF_RANGE_PACK_ID'] = 'VALUE_OUT_OF_RANGE_PACK_ID';
        $errorMap['VALUE_OUT_OF_RANGE_CONTENTS'] = 'VALUE_OUT_OF_RANGE_CONTENTS';
        $errorMap['VALUE_OUT_OF_RANGE_PACKING'] = 'VALUE_OUT_OF_RANGE_PACKING';
        $errorMap['VALUE_OUT_OF_RANGE_NOTE_CLIENT'] = 'VALUE_OUT_OF_RANGE_NOTE_CLIENT';
        $errorMap['VALUE_OUT_OF_RANGE_CLIENT_FIELD'] = 'VALUE_OUT_OF_RANGE_CLIENT_FIELD';
        $errorMap['VALUE_OUT_OF_RANGE_ADDRESS_FIELD'] = 'VALUE_OUT_OF_RANGE_ADDRESS_FIELD';
        $errorMap['VALUE_OUT_OF_RANGE_REF1'] = 'VALUE_OUT_OF_RANGE_REF1';
        $errorMap['VALUE_OUT_OF_RANGE_REF2'] = 'VALUE_OUT_OF_RANGE_REF2';
        $errorMap['VALUE_OUT_OF_RANGE_DEFERRED_DELIVERY_WORK_DAYS'] = 'VALUE_OUT_OF_RANGE_DEFERRED_DELIVERY_WORK_DAYS';
        
    }
    
    public function getErrorMap(){
        return $this->errorMap;
    }
}

?>
